/* @type {import('next').NextConfig} */
/* eslint-disable no-undef */
const nextConfig = {
  env: {
    FEATURE_PRACTICE_ADAPTIVE_DIFFICULTY: process.env.FEATURE_PRACTICE_ADAPTIVE_DIFFICULTY,
    FEATURE_AUDIO_WEB_WORKER: process.env.FEATURE_AUDIO_WEB_WORKER,
    FEATURE_UI_INTONATION_HEATMAPS: process.env.FEATURE_UI_INTONATION_HEATMAPS,
    FEATURE_SOCIAL_PRACTICE_ROOMS: process.env.FEATURE_SOCIAL_PRACTICE_ROOMS,
    FEATURE_TELEMETRY_ACCURACY: process.env.FEATURE_TELEMETRY_ACCURACY,
    FEATURE_PRACTICE_ZEN_MODE: process.env.FEATURE_PRACTICE_ZEN_MODE,
    FEATURE_PRACTICE_AUTO_START: process.env.FEATURE_PRACTICE_AUTO_START,
    FEATURE_PRACTICE_EXERCISE_RECOMMENDER: process.env.FEATURE_PRACTICE_EXERCISE_RECOMMENDER,
    FEATURE_PRACTICE_ACHIEVEMENT_SYSTEM: process.env.FEATURE_PRACTICE_ACHIEVEMENT_SYSTEM,
  },
  typescript: {
    ignoreBuildErrors: true,
  },
  images: {
    unoptimized: true,
  },
}

export default nextConfig
